# Generated by Django 3.1.12 on 2021-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210607_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='default_price',
            field=models.IntegerField(default=1),
        ),
    ]
